export const TEST_REDUX = 'TEST_REDUX';
export const TEST_REDUX_SUCCESS = 'TEST_REDUX_SUCCESS';
export const TEST_REDUX_FAIL = 'TEST_REDUX_FAIL';

export const GET_TEST_REDUX = 'GET_TEST_REDUX';
export const GET_TEST_REDUX_SUCCESS = 'GET_TEST_REDUX_SUCCESS';
export const GET_TEST_REDUX_FAIL = 'GET_TEST_REDUX_FAIL';

export const UPDATE_TEST_REDUX = 'UPDATE_TEST_REDUX';
export const UPDATE_TEST_REDUX_SUCCESS = 'UPDATE_TEST_REDUX_SUCCESS';
export const UPDATE_TEST_REDUX_FAIL = 'UPDATE_TEST_REDUX_FAIL';

// APP Reudx
export const GET_VALUE = 'GET_VALUE'
export const GET_VALUE_SUCCESS = 'GET_VALUE_SUCCESS'
export const GET_VALUE_FAIL = 'GET_VALUE_FAIL'

export const SET_VALUE = 'SET_VALUE'

// Giphy
export const GET_TRENDING_GIFS = 'GET_TRENDING_GIFS';
export const GET_TRENDING_GIFS_SUCCESS = 'GET_TRENDING_GIFS_SUCCESS';
export const GET_TRENDING_GIFS_FAIL = 'GET_TRENDING_GIFS_FAIL';

export const GET_MORE_TRENDING_GIFS = 'GET_MORE_TRENDING_GIFS';
export const GET_MORE_TRENDING_GIFS_SUCCESS = 'GET_MORE_TRENDING_GIFS_SUCCESS';
export const GET_MORE_TRENDING_GIFS_FAIL = 'GET_MORE_TRENDING_GIFS_FAIL';

export const GIPHY_LOADING = 'GIPHY_LOADING';

export const GIPHY_SEARCH = 'GIPHY_SEARCH';
export const GIPHY_SEARCH_SUCCESS = 'GIPHY_SEARCH_SUCCESS';
export const GIPHY_SEARCH_FAIL = 'GIPHY_SEARCH_FAIL';